// <auto-generated />
using System;
using ItransitionCourseProject.DataBase;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ItransitionCourseProject.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20260723132832_V1")]
    partial class V1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ItransitionCourseProject.Models.Attribute", b =>
                {
                    b.Property<Guid>("AttributeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AttributeName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsSystem")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.HasKey("AttributeId");

                    b.HasIndex("AttributeName")
                        .IsUnique();

                    b.ToTable("Attributes");
                });

            modelBuilder.Entity("ItransitionCourseProject.Models.AttributeValue", b =>
                {
                    b.Property<Guid>("AttributeValueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AttributeId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProfileCandidateId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.HasKey("AttributeValueId");

                    b.HasIndex("ProfileCandidateId", "AttributeId")
                        .IsUnique();

                    b.ToTable("AttributeValues");
                });

            modelBuilder.Entity("ItransitionCourseProject.Models.CV", b =>
                {
                    b.Property<Guid>("CvId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("PositionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProfileCandidateId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("PublishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Draft");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.HasKey("CvId");

                    b.HasIndex("PositionId");

                    b.HasIndex("ProfileCandidateId", "PositionId")
                        .IsUnique();

                    b.HasIndex("Status", "PublishedAt");

                    b.ToTable("Cvs");
                });

            modelBuilder.Entity("ItransitionCourseProject.Models.CvLike", b =>
                {
                    b.Property<Guid>("CvId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RecruiterId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("CvId", "RecruiterId");

                    b.HasIndex("RecruiterId");

                    b.ToTable("CvLikes");
                });

            modelBuilder.Entity("ItransitionCourseProject.Models.Discussion", b =>
                {
                    b.Property<Guid>("DiscussionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AuthorDisplayName")
                        .IsRequired()
                        .HasMaxLength(201)
                        .HasColumnType("character varying(201)");

                    b.Property<Guid?>("AuthorId")
                        .HasColumnType("uuid");

                    b.Property<string>("ContentMarkdown")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("PositionId")
                        .HasColumnType("uuid");

                    b.HasKey("DiscussionId");

                    b.HasIndex("AuthorId");

                    b.HasIndex("PositionId", "CreatedAt");

                    b.ToTable("Discussions");
                });

            modelBuilder.Entity("ItransitionCourseProject.Models.Position", b =>
                {
                    b.Property<Guid>("PositionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("ShortDescription")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.HasKey("PositionId");

                    b.ToTable("Positions");
                });

            modelBuilder.Entity("ItransitionCourseProject.Models.PositionAttributeBinding", b =>
                {
                    b.Property<Guid>("PositionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("AttributeId")
                        .HasColumnType("uuid");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("boolean");

                    b.HasKey("PositionId", "AttributeId");

                    b.HasIndex("AttributeId");

                    b.ToTable("PositionAttributeBindings");
                });

            modelBuilder.Entity("ItransitionCourseProject.Models.PositionProjectTag", b =>
                {
                    b.Property<Guid>("PositionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TechnologyTagId")
                        .HasColumnType("uuid");

                    b.HasKey("PositionId", "TechnologyTagId");

                    b.HasIndex("TechnologyTagId");

                    b.ToTable("PositionProjectTags");
                });

            modelBuilder.Entity("ItransitionCourseProject.Models.ProfileAttributeBinding", b =>
                {
                    b.Property<Guid>("ProfileCandidateId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("AttributeId")
                        .HasColumnType("uuid");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.HasKey("ProfileCandidateId", "AttributeId");

                    b.HasIndex("AttributeId");

                    b.ToTable("ProfileAttributeBindings");
                });

            modelBuilder.Entity("ItransitionCourseProject.Models.ProfileCandidate", b =>
                {
                    b.Property<Guid>("ProfileCandidateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.HasKey("ProfileCandidateId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("ProfileCandidates");
                });

            modelBuilder.Entity("ItransitionCourseProject.Models.TechnologyTag", b =>
                {
                    b.Property<Guid>("TechnologyTagId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("TechnologyTagId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("TechnologyTags");
                });

            modelBuilder.Entity("ItransitionCourseProject.Models.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Company")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsBlocked")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("ProfilePicPublicId")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("ProfilePicUrl")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Theme")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasDefaultValue("Light");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.HasKey("UserId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ItransitionCourseProject.Models.UserExternalLogin", b =>
                {
                    b.Property<string>("Provider")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Subject")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Provider", "Subject");

                    b.HasIndex("UserId", "Provider")
                        .IsUnique();

                    b.ToTable("UserExternalLogins");
                });

            modelBuilder.Entity("ItransitionCourseProject.Models.AttributeValue", b =>
                {
                    b.HasOne("ItransitionCourseProject.Models.ProfileAttributeBinding", "BindingForValue")
                        .WithOne("ValueForBinding")
                        .HasForeignKey("ItransitionCourseProject.Models.AttributeValue", "ProfileCandidateId", "AttributeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BindingForValue");
                });

            modelBuilder.Entity("ItransitionCourseProject.Models.CV", b =>
                {
                    b.HasOne("ItransitionCourseProject.Models.Position", "PositionForCv")
                        .WithMany("CvForPosition")
                        .HasForeignKey("PositionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ItransitionCourseProject.Models.ProfileCandidate", "ProfileForCv")
                        .WithMany("CvForProfile")
                        .HasForeignKey("ProfileCandidateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PositionForCv");

                    b.Navigation("ProfileForCv");
                });

            modelBuilder.Entity("ItransitionCourseProject.Models.CvLike", b =>
                {
                    b.HasOne("ItransitionCourseProject.Models.CV", "CvForLike")
                        .WithMany("LikeForCv")
                        .HasForeignKey("CvId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ItransitionCourseProject.Models.User", "RecruiterForLike")
                        .WithMany("CvLikeForUser")
                        .HasForeignKey("RecruiterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CvForLike");

                    b.Navigation("RecruiterForLike");
                });

            modelBuilder.Entity("ItransitionCourseProject.Models.Discussion", b =>
                {
                    b.HasOne("ItransitionCourseProject.Models.User", "AuthorForDiscussion")
                        .WithMany("DiscussionForUser")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ItransitionCourseProject.Models.Position", "PositionForDiscussion")
                        .WithMany("DiscussionForPosition")
                        .HasForeignKey("PositionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AuthorForDiscussion");

                    b.Navigation("PositionForDiscussion");
                });

            modelBuilder.Entity("ItransitionCourseProject.Models.PositionAttributeBinding", b =>
                {
                    b.HasOne("ItransitionCourseProject.Models.Attribute", "AttributeForBinding")
                        .WithMany("PositionBindingForAttribute")
                        .HasForeignKey("AttributeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ItransitionCourseProject.Models.Position", "PositionForBinding")
                        .WithMany("AttributeBindingForPosition")
                        .HasForeignKey("PositionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AttributeForBinding");

                    b.Navigation("PositionForBinding");
                });

            modelBuilder.Entity("ItransitionCourseProject.Models.PositionProjectTag", b =>
                {
                    b.HasOne("ItransitionCourseProject.Models.Position", "PositionForBinding")
                        .WithMany("ProjectTagBindingForPosition")
                        .HasForeignKey("PositionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ItransitionCourseProject.Models.TechnologyTag", "TechnologyTagForBinding")
                        .WithMany("PositionBindingForTechnologyTag")
                        .HasForeignKey("TechnologyTagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PositionForBinding");

                    b.Navigation("TechnologyTagForBinding");
                });

            modelBuilder.Entity("ItransitionCourseProject.Models.ProfileAttributeBinding", b =>
                {
                    b.HasOne("ItransitionCourseProject.Models.Attribute", "AttributeForBinding")
                        .WithMany("ProfileBindingForAttribute")
                        .HasForeignKey("AttributeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ItransitionCourseProject.Models.ProfileCandidate", "ProfileForBinding")
                        .WithMany("BindingForProfile")
                        .HasForeignKey("ProfileCandidateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AttributeForBinding");

                    b.Navigation("ProfileForBinding");
                });

            modelBuilder.Entity("ItransitionCourseProject.Models.ProfileCandidate", b =>
                {
                    b.HasOne("ItransitionCourseProject.Models.User", "UserForProfile")
                        .WithOne("ProfileForUser")
                        .HasForeignKey("ItransitionCourseProject.Models.ProfileCandidate", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserForProfile");
                });

            modelBuilder.Entity("ItransitionCourseProject.Models.UserExternalLogin", b =>
                {
                    b.HasOne("ItransitionCourseProject.Models.User", "UserForExternalLogin")
                        .WithMany("ExternalLoginForUser")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserForExternalLogin");
                });

            modelBuilder.Entity("ItransitionCourseProject.Models.Attribute", b =>
                {
                    b.Navigation("PositionBindingForAttribute");

                    b.Navigation("ProfileBindingForAttribute");
                });

            modelBuilder.Entity("ItransitionCourseProject.Models.CV", b =>
                {
                    b.Navigation("LikeForCv");
                });

            modelBuilder.Entity("ItransitionCourseProject.Models.Position", b =>
                {
                    b.Navigation("AttributeBindingForPosition");

                    b.Navigation("CvForPosition");

                    b.Navigation("DiscussionForPosition");

                    b.Navigation("ProjectTagBindingForPosition");
                });

            modelBuilder.Entity("ItransitionCourseProject.Models.ProfileAttributeBinding", b =>
                {
                    b.Navigation("ValueForBinding");
                });

            modelBuilder.Entity("ItransitionCourseProject.Models.ProfileCandidate", b =>
                {
                    b.Navigation("BindingForProfile");

                    b.Navigation("CvForProfile");
                });

            modelBuilder.Entity("ItransitionCourseProject.Models.TechnologyTag", b =>
                {
                    b.Navigation("PositionBindingForTechnologyTag");
                });

            modelBuilder.Entity("ItransitionCourseProject.Models.User", b =>
                {
                    b.Navigation("CvLikeForUser");

                    b.Navigation("DiscussionForUser");

                    b.Navigation("ExternalLoginForUser");

                    b.Navigation("ProfileForUser");
                });
#pragma warning restore 612, 618
        }
    }
}
